import type { CountryCapability, CountryId, CountryRegistryEntry } from "./model";

const capability = (level: CountryCapability["level"], status: CountryCapability["status"], sourceIds: string[], note: string): CountryCapability => ({ level, status, sourceIds, note });

export const licenceRegistry = {
  "us-public-domain": { name: "US Government public-domain material", url: "https://www.bls.gov/bls/linksite.htm", commercialReuse: true, attributionRequired: false, status: "VERIFIED" },
  "onet-cc-by-4": { name: "O*NET Database licence (CC BY 4.0)", url: "https://www.onetcenter.org/database.html#license", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "abs-cc-by-4": { name: "ABS Copyright and Creative Commons", url: "https://www.abs.gov.au/copyright", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "ca-open-government": { name: "Open Government Licence – Canada", url: "https://open.canada.ca/en/open-government-licence-canada", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "uk-ogl-3": { name: "Open Government Licence v3.0", url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "nz-govt-open-access": { name: "New Zealand Government CC BY 4.0 / NZGOAL", url: "https://www.stats.govt.nz/about-us/copyright/", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "nz-tahatu-cc-by-4": { name: "Tahatū / TEC Creative Commons Attribution 4.0", url: "https://tahatu.govt.nz/using-our-content", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "sg-open-data-1": { name: "Singapore Open Data Licence v1.0", url: "https://data.gov.sg/open-data-licence", commercialReuse: true, attributionRequired: true, status: "VERIFIED" },
  "sg-government-reference": { name: "Singapore Government reference material", url: "https://www.skillsfuture.gov.sg/skills-framework", commercialReuse: false, attributionRequired: true, status: "SOURCE_REVIEW_REQUIRED" },
} as const;

export const sourceRegistry = {
  "us-bls-oews-2025": { publisher: "US Bureau of Labor Statistics", dataset: "Occupational Employment and Wage Statistics", url: "https://www.bls.gov/oes/", licenceId: "us-public-domain", updateCadence: "ANNUAL", parser: "seed/us-oews", quality: "PRIMARY_OFFICIAL" },
  "us-bls-projections-2024-34": { publisher: "US Bureau of Labor Statistics", dataset: "Employment Projections 2024–2034", url: "https://www.bls.gov/emp/", licenceId: "us-public-domain", updateCadence: "ANNUAL", parser: "seed/us-projections", quality: "PRIMARY_OFFICIAL" },
  "us-onet-30-3": { publisher: "O*NET Resource Center", dataset: "O*NET Database 30.3", url: "https://www.onetcenter.org/database.html", licenceId: "onet-cc-by-4", updateCadence: "QUARTERLY", parser: "seed/onet", quality: "PRIMARY_OFFICIAL" },
  "au-jsa-profiles-2026": { publisher: "Jobs and Skills Australia / ABS", dataset: "Occupation profiles", url: "https://www.jobsandskills.gov.au/data/occupation-and-industry-profiles", licenceId: "abs-cc-by-4", updateCadence: "QUARTERLY", parser: "seed/au-jsa", quality: "PRIMARY_OFFICIAL" },
  "ca-job-bank-wages-2025": { publisher: "Government of Canada Job Bank", dataset: "National wages", url: "https://www.jobbank.gc.ca/trend-analysis/search-wages", licenceId: "ca-open-government", updateCadence: "ANNUAL", parser: "seed/ca-job-bank", quality: "PRIMARY_OFFICIAL" },
  "ca-job-bank-requirements-2025": { publisher: "Government of Canada Job Bank", dataset: "Job requirements", url: "https://www.jobbank.gc.ca/trend-analysis/search-job-requirements", licenceId: "ca-open-government", updateCadence: "ANNUAL", parser: "seed/ca-job-bank", quality: "PRIMARY_OFFICIAL" },
  "uk-ons-ashe-2025": { publisher: "Office for National Statistics", dataset: "Annual Survey of Hours and Earnings 2025 provisional", url: "https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/earningsandworkinghours", licenceId: "uk-ogl-3", updateCadence: "ANNUAL", parser: "seed/uk-ashe", quality: "PRIMARY_OFFICIAL" },
  "uk-national-careers-service": { publisher: "National Careers Service", dataset: "Career profiles", url: "https://nationalcareers.service.gov.uk/explore-careers", licenceId: "uk-ogl-3", updateCadence: "QUARTERLY_REVIEW", parser: "seed/uk-ncs", quality: "OFFICIAL_BENCHMARK" },
  "nz-stats-nol": { publisher: "Stats NZ", dataset: "National Occupation List 3.0", url: "https://www.stats.govt.nz/methods/about-the-national-occupation-list", licenceId: "nz-govt-open-access", updateCadence: "ANNUAL", parser: "seed/nz-nol", quality: "PRIMARY_OFFICIAL" },
  "nz-tahatu-careers-2026": { publisher: "Tertiary Education Commission", dataset: "Tahatū Career Navigator occupation profiles", url: "https://tahatu.govt.nz/", licenceId: "nz-tahatu-cc-by-4", updateCadence: "QUARTERLY_REVIEW", parser: "seed/nz-tahatu", quality: "OFFICIAL_BENCHMARK" },
  "sg-ssoc-2024": { publisher: "Singapore Department of Statistics", dataset: "Singapore Standard Occupational Classification 2024", url: "https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc", licenceId: "sg-open-data-1", updateCadence: "RELEASE_DRIVEN", parser: "seed/sg-ssoc", quality: "PRIMARY_OFFICIAL" },
  "sg-mom-occupational-wages-2024-open": { publisher: "Singapore Ministry of Manpower", dataset: "Resident Occupational Wages, June 2024", url: "https://data.gov.sg/datasets/d_9917e751f7498502f70052a940a3f312/view", licenceId: "sg-open-data-1", updateCadence: "ANNUAL", parser: "seed/sg-data-gov", quality: "PRIMARY_OFFICIAL" },
  "sg-skillsfuture-frameworks": { publisher: "SkillsFuture Singapore", dataset: "Skills Frameworks", url: "https://www.skillsfuture.gov.sg/skills-framework", licenceId: "sg-government-reference", updateCadence: "RELEASE_DRIVEN", parser: "reference/sg-skillsfuture", quality: "OFFICIAL_BENCHMARK" },
} as const;

export const countryRegistry: Record<CountryId, CountryRegistryEntry> = {
  us: {
    id: "us", iso2: "US", slug: "us", label: "United States", shortLabel: "USA", aliases: ["united states", "usa", "us", "america"], locale: "en-US", currency: "USD", enabled: true, pilot: false,
    occupationTaxonomy: { id: "ONET_SOC", label: "O*NET-SOC", version: "2019" },
    capabilities: { salary: capability("EXCELLENT", "AVAILABLE", ["us-bls-oews-2025"], "Annual national percentiles."), employment: capability("EXCELLENT", "AVAILABLE", ["us-bls-oews-2025"], "National employment where loaded."), outlook: capability("EXCELLENT", "AVAILABLE", ["us-bls-projections-2024-34"], "Ten-year projections and openings."), education: capability("GOOD", "AVAILABLE", ["us-onet-30-3"], "Typical route."), licensing: capability("LIMITED", "AVAILABLE", ["us-onet-30-3"], "Occupation-level summary only."), subnational: capability("GOOD", "NOT_AVAILABLE", ["us-bls-oews-2025"], "Supported by source, not included in current coverage.") },
    trustSignals: ["O*NET 30.3", "BLS May 2025", "2024–34 outlook"], sourceNote: "United States figures: BLS OEWS May 2025 and 2024–34 employment projections.", methodNote: "Wages and outlook from BLS. Skills, interests and work context from O*NET.", footerSource: "O*NET 30.3 · BLS OEWS May 2025 · BLS 2024–34 projections", workSignalNote: "Work signals are native O*NET occupation percentiles.", momentumMetric: "annualOpenings", momentumLabel: "More annual openings", minimumCoverage: { careers: 20, annualSalaryFacts: 20, mappingsReviewed: 20 },
  },
  au: {
    id: "au", iso2: "AU", slug: "au", label: "Australia", shortLabel: "Australia", aliases: ["australia", "aus", "au"], locale: "en-AU", currency: "AUD", enabled: true, pilot: false,
    occupationTaxonomy: { id: "ANZSCO", label: "ANZSCO", version: "2022" },
    capabilities: { salary: capability("GOOD", "AVAILABLE", ["au-jsa-profiles-2026"], "Weekly and hourly medians."), employment: capability("GOOD", "AVAILABLE", ["au-jsa-profiles-2026"], "National employment where loaded."), outlook: capability("LIMITED", "NOT_AVAILABLE", ["au-jsa-profiles-2026"], "No US-style ten-year value is substituted."), education: capability("GOOD", "AVAILABLE", ["au-jsa-profiles-2026"], "Typical route."), licensing: capability("LIMITED", "AVAILABLE", ["au-jsa-profiles-2026"], "Summary, not legal advice."), subnational: capability("LIMITED", "NOT_AVAILABLE", ["au-jsa-profiles-2026"], "Not included in current coverage.") },
    trustSignals: ["Jobs and Skills Australia", "ABS earnings · May 2025", "Employment · Feb 2026"], sourceNote: "Australian figures: Jobs and Skills Australia occupation profiles using ABS earnings (May 2025). Annual figures are weekly medians × 52.", methodNote: "Earnings from Jobs and Skills Australia / ABS. Work signals from O*NET as a clearly labelled proxy.", footerSource: "JSA / ABS · earnings May 2025 · employment February 2026", workSignalNote: "O*NET signals are retained as an occupation-level proxy; labour-market facts are Australian.", momentumMetric: "employmentChange", momentumLabel: "Stronger recent job gain", minimumCoverage: { careers: 20, annualSalaryFacts: 20, mappingsReviewed: 20 },
  },
  ca: {
    id: "ca", iso2: "CA", slug: "ca", label: "Canada", shortLabel: "Canada", aliases: ["canada", "ca"], locale: "en-CA", currency: "CAD", enabled: true, pilot: false,
    occupationTaxonomy: { id: "NOC", label: "NOC", version: "2021" },
    capabilities: { salary: capability("GOOD", "AVAILABLE", ["ca-job-bank-wages-2025"], "National hourly median."), employment: capability("LIMITED", "NOT_AVAILABLE", [], "No national occupation count is loaded."), outlook: capability("GOOD", "NOT_APPLICABLE", [], "Outlook varies by province/economic region."), education: capability("GOOD", "AVAILABLE", ["ca-job-bank-requirements-2025"], "Typical requirements."), licensing: capability("LIMITED", "AVAILABLE", ["ca-job-bank-requirements-2025"], "Province-specific detail required."), subnational: capability("GOOD", "NOT_AVAILABLE", ["ca-job-bank-wages-2025"], "Source supports it; not included in current coverage.") },
    trustSignals: ["Government of Canada Job Bank", "Statistics Canada inputs", "Wages updated Nov 2025"], sourceNote: "Canadian figures: Government of Canada Job Bank national median hourly wages. Annual figures are hourly median × 40 hours × 52 weeks; outlook is not silently nationalised.", methodNote: "Wages and requirements from Canada Job Bank. Work signals from O*NET as a clearly labelled proxy.", footerSource: "Canada Job Bank · national wages updated November 2025", workSignalNote: "O*NET signals are retained as an occupation-level proxy; labour-market facts are Canadian.", momentumMetric: null, momentumLabel: "National outlook", minimumCoverage: { careers: 20, annualSalaryFacts: 20, mappingsReviewed: 20 },
  },
  uk: {
    id: "uk", iso2: "GB", slug: "uk", label: "United Kingdom", shortLabel: "United Kingdom", aliases: ["united kingdom", "uk", "great britain", "britain"], locale: "en-GB", currency: "GBP", enabled: true, pilot: false,
    occupationTaxonomy: { id: "UK_SOC", label: "SOC", version: "2020" },
    capabilities: { salary: capability("GOOD", "AVAILABLE", ["uk-ons-ashe-2025", "uk-national-careers-service"], "ASHE medians; explicit benchmark where a profile range is used."), employment: capability("LIMITED", "NOT_AVAILABLE", [], "Not included in current coverage."), outlook: capability("LIMITED", "AVAILABLE", ["uk-ons-ashe-2025"], "Annual earnings change where available."), education: capability("GOOD", "AVAILABLE", ["uk-national-careers-service"], "Official pathway summary."), licensing: capability("LIMITED", "AVAILABLE", ["uk-national-careers-service"], "Summary, not legal advice."), subnational: capability("LIMITED", "NOT_AVAILABLE", [], "Not included in current coverage.") },
    trustSignals: ["ONS ASHE 2025", "SOC 2020", "National Careers Service"], sourceNote: "UK figures: ONS ASHE 2025 provisional earnings where available and clearly labelled National Careers Service range midpoints for newly added profiles.", methodNote: "Earnings from ONS ASHE and pathways from the National Careers Service. Work signals from O*NET as a clearly labelled proxy.", footerSource: "ONS ASHE 2025 provisional · National Careers Service", workSignalNote: "O*NET signals are retained as an occupation-level proxy; labour-market facts are UK data.", momentumMetric: "earningsChange", momentumLabel: "Faster earnings growth", minimumCoverage: { careers: 20, annualSalaryFacts: 20, mappingsReviewed: 20 },
  },
  nz: {
    id: "nz", iso2: "NZ", slug: "nz", label: "New Zealand", shortLabel: "New Zealand", aliases: ["new zealand", "nz", "aotearoa"], locale: "en-NZ", currency: "NZD", enabled: true, pilot: false,
    occupationTaxonomy: { id: "NOL", label: "NOL", version: "3.0" },
    capabilities: { salary: capability("GOOD", "AVAILABLE", ["nz-tahatu-careers-2026"], "Published pay ranges displayed as transparent midpoints."), employment: capability("LIMITED", "NOT_AVAILABLE", [], "No occupation count is loaded."), outlook: capability("LIMITED", "NOT_AVAILABLE", [], "No stale national projection is substituted."), education: capability("GOOD", "AVAILABLE", ["nz-tahatu-careers-2026"], "Tahatū pathway summaries."), licensing: capability("GOOD", "AVAILABLE", ["nz-tahatu-careers-2026"], "Occupation-level registration summary; regulator details still govern."), subnational: capability("LIMITED", "NOT_AVAILABLE", [], "Not included in current coverage.") },
    trustSignals: ["Stats NZ NOL 3.0", "Tahatū Career Navigator", "CC BY 4.0"], sourceNote: "New Zealand figures: Tahatū Career Navigator published pay ranges and pathways, mapped through Stats NZ NOL 3.0. Annual headline figures are clearly labelled range midpoints.", methodNote: "Career ranges and pathways from Tahatū / TEC; occupation identity from Stats NZ NOL. Work signals remain clearly labelled O*NET occupation proxies.", footerSource: "Stats NZ NOL 3.0 · Tahatū / TEC · reviewed August 2026", workSignalNote: "O*NET signals are retained as an occupation-level proxy; labour-market facts are New Zealand data.", momentumMetric: null, momentumLabel: "National outlook", minimumCoverage: { careers: 20, annualSalaryFacts: 20, mappingsReviewed: 20 },
  },
  sg: {
    id: "sg", iso2: "SG", slug: "sg", label: "Singapore", shortLabel: "Singapore", aliases: ["singapore", "sg"], locale: "en-SG", currency: "SGD", enabled: true, pilot: false,
    occupationTaxonomy: { id: "SSOC", label: "SSOC", version: "2024" },
    capabilities: { salary: capability("GOOD", "AVAILABLE", ["sg-mom-occupational-wages-2024-open"], "Open-data monthly gross wage medians for covered resident occupations."), employment: capability("LIMITED", "NOT_AVAILABLE", [], "No granular occupation count is loaded."), outlook: capability("LIMITED", "NOT_AVAILABLE", [], "No directly comparable occupation projection is loaded."), education: capability("GOOD", "AVAILABLE", ["sg-skillsfuture-frameworks"], "Official Skills Framework pathway summaries."), licensing: capability("LIMITED", "AVAILABLE", ["sg-skillsfuture-frameworks"], "High-level regulated-role notes only."), subnational: capability("UNAVAILABLE", "NOT_APPLICABLE", [], "City-state; no subnational layer planned for V1.") },
    trustSignals: ["MOM occupational wages", "SSOC 2024", "Singapore Open Data Licence"], sourceNote: "Singapore figures: Ministry of Manpower Resident Occupational Wages, June 2024, published through data.gov.sg under the Singapore Open Data Licence. Annual figures are monthly gross medians × 12.", methodNote: "Wages from the open MOM dataset; mappings from SSOC 2024; education context from SkillsFuture. Missing occupations stay unavailable.", footerSource: "MOM Resident Occupational Wages June 2024 · SSOC 2024", workSignalNote: "O*NET signals are retained as an occupation-level proxy; labour-market facts are Singapore data.", momentumMetric: null, momentumLabel: "Occupation outlook", minimumCoverage: { careers: 20, annualSalaryFacts: 18, mappingsReviewed: 20 },
  },
};
