import { buildRecord, type SeedRecord } from "./build-record";
import type { CareerKey, CountryAdapter } from "../model";

const common = { countryId: "uk", taxonomyId: "UK_SOC", taxonomyVersion: "2020", sourceId: "uk-ons-ashe-2025", releaseId: "2025-provisional", referencePeriod: "2025 provisional", reviewedAt: "2026-08-14", metricSourceIds: { outlook: "uk-ons-ashe-2025", education: "uk-national-careers-service" } } as const;
const seeds: Record<CareerKey, Omit<SeedRecord, keyof typeof common | "key">> = {
  rn: { code: "2237", salary: { value: 42300, unit: "GBP/year" }, hourly: 22.32, earningsChangePercent: 4, education: "Approved nursing degree", credential: "NMC registration required" },
  software: { code: "2134", salary: { value: 56914, unit: "GBP/year" }, hourly: 29.58, earningsChangePercent: 4.2, education: "Degree or apprenticeship", credential: "Experience / portfolio valued" },
  electrician: { code: "5241", salary: { value: 39647, unit: "GBP/year" }, hourly: 19.2, earningsChangePercent: 2.7, education: "College course or apprenticeship", credential: "Industry card / certification expected" },
  accountant: { code: "2421", salary: { value: 50062, unit: "GBP/year" }, hourly: 26.02, earningsChangePercent: 0.6, education: "Degree or professional route", credential: "Chartered qualification varies" },
  dental: { code: "3213", localTitle: "Dental nurses and dental health professionals", mappingQuality: "BROADER", salarySourceId: "uk-national-careers-service", salaryReleaseId: "accessed-2026-08-14", salaryReferencePeriod: "Current published range; accessed 14 August 2026", salary: { value: 44500, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 32000, high: 57000 }, education: "Approved diploma or degree", credential: "GDC registration required" },
  sonographer: { code: "2254", salary: { value: 48439, unit: "GBP/year" }, hourly: 24.68, earningsChangePercent: 6.9, education: "Degree plus ultrasound study", credential: "CASE-recognised qualification" },
  plumber: { code: "5315", salary: { value: 37881, unit: "GBP/year" }, hourly: 18.18, earningsChangePercent: -0.6, education: "College course or apprenticeship", credential: "Gas Safe registration for gas work" },
  designer: { code: "2142", salary: { value: 32510, unit: "GBP/year" }, hourly: 17.38, earningsChangePercent: 2.5, education: "Degree, college or apprenticeship", credential: "Portfolio typically expected" },
  security: { code: "2135", salary: { value: 54647, unit: "GBP/year" }, hourly: 27.62, earningsChangePercent: 12.5, education: "Degree or apprenticeship", credential: "Experience / certification valued" },
  teacher: { code: "2313", salary: { value: 47632, unit: "GBP/year" }, hourly: 28.95, earningsChangePercent: 5, education: "Degree plus teacher training", credential: "QTS normally required" },
  enrolledNurse: { code: "-", localTitle: "No direct regulated equivalent", mappingQuality: "NO_EQUIVALENT", salarySourceId: "uk-national-careers-service", salary: { value: 34000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 30000, high: 38000 }, education: "Nursing associate route is the closest comparator", credential: "NMC registration for nursing associates" },
  radiologicTech: { code: "2254", localTitle: "Radiographer", mappingQuality: "STRONG", salarySourceId: "uk-national-careers-service", salary: { value: 40500, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 31000, high: 50000 }, education: "Approved radiography degree", credential: "HCPC registration required" },
  occupationalTherapist: { code: "2222", salarySourceId: "uk-national-careers-service", salary: { value: 40500, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 31000, high: 50000 }, education: "Approved occupational therapy degree", credential: "HCPC registration required" },
  physiotherapist: { code: "2221", salarySourceId: "uk-national-careers-service", salary: { value: 43000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 31000, high: 55000 }, education: "Approved physiotherapy degree", credential: "HCPC registration required" },
  hvac: { code: "5225", localTitle: "Refrigeration and Air-conditioning Installer", salarySourceId: "uk-national-careers-service", salary: { value: 36500, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 28000, high: 45000 }, education: "College course or apprenticeship", credential: "F-gas certification required for regulated work" },
  welder: { code: "5213", salarySourceId: "uk-national-careers-service", salary: { value: 35000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 25000, high: 45000 }, education: "College course or apprenticeship", credential: "Industry coding certificates valued" },
  carpenter: { code: "5316", localTitle: "Carpenter and Joiner", salarySourceId: "uk-national-careers-service", salary: { value: 34500, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 24000, high: 45000 }, education: "College course or apprenticeship", credential: "CSCS card commonly expected" },
  automotiveTech: { code: "5231", localTitle: "Motor Mechanic", salarySourceId: "uk-national-careers-service", salary: { value: 32000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 22000, high: 42000 }, education: "College course or apprenticeship", credential: "Manufacturer and industry certification valued" },
  financialAnalyst: { code: "2433", mappingQuality: "STRONG", salarySourceId: "uk-national-careers-service", salary: { value: 49000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 28000, high: 70000 }, education: "Degree or professional route", credential: "FCA-regulated roles may require approval" },
  systemsAnalyst: { code: "2133", salarySourceId: "uk-national-careers-service", salary: { value: 39000, unit: "GBP/year", basis: "RANGE_MIDPOINT", low: 23000, high: 55000 }, education: "Degree or apprenticeship", credential: "Experience and certification valued" },
};

export const ukAdapter: CountryAdapter = { countryId: "uk", schemaVersion: "1.0", records: Object.fromEntries(Object.entries(seeds).map(([key, seed]) => [key, buildRecord({ ...common, ...seed, key: key as CareerKey })])) as CountryAdapter["records"] };
